1.- Crear una matriz 3x3 con valores de 0 a 8


In [34]:
import numpy as np

In [35]:
array = np.array([[0, 1, 2], [3,4,5], [6,7,8]])

In [30]:
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


2.- Crear una matriz identidad de 6x6 utilizando la función .identity().

In [48]:
matriz = np.identity(6)

In [49]:
print(matriz)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
